;;; Exercise 8.6

(define (words wd)
  (every letter-word wd))

(define (letter-word x)
  (cond ((equal? x 'a) 'Alfa)
         ((equal? x 'b) 'Bravo)
         ((equal? x 'c) 'Charlie)
         ((equal? x 'd) 'Delta)
         ((equal? x 'e) 'Echo)
         ((equal? x 'f) 'Foxtrot)
         ((equal? x 'g) 'Golf)
         ((equal? x 'h) 'Hotel)
         ((equal? x 'i) 'India)
         ((equal? x 'j) 'Juliett)
         ((equal? x 'k) 'Kilo)
         ((equal? x 'l) 'Lima)
         ((equal? x 'm) 'Mike)
         ((equal? x 'n) 'November)
         ((equal? x 'o) 'Oscar)
         ((equal? x 'p) 'Papa)
         ((equal? x 'q) 'Quebec)
         ((equal? x 'r) 'Romeo)
         ((equal? x 's) 'Sierra)
         ((equal? x 't) 'Tango)
         ((equal? x 'u) 'Uniform)
         ((equal? x 'v) 'Victor)
         ((equal? x 'w) 'Whiskey)
         ((equal? x 'x) 'Xray)
         ((equal? x 'y) 'Yankee)
         (else (equal? x 'z) 'Zulu)))